name: Relase on pocketbase/release
on:
  schedule:
    - cron: "0 0 * * 1"
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch latest pocketbase version
        id: pocketbase
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          set -euo pipefail
          api="https://api.github.com/repos/pocketbase/pocketbase/releases/latest"
          tag=$(curl -fsSL \
            -H "Authorization: Bearer $GH_TOKEN" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "$api" | jq -r '.tag_name')
          if [ -z "${tag:-}" ] || [ "$tag" = "null" ]; then
            echo "Failed to fetch latest release" >&2
            exit 1
          fi
          echo "version=$tag" >> "$GITHUB_OUTPUT"

      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to docker-hub
        uses: docker/login-action@v2
        with:
          username: smilingxinyi
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            smilingxinyi/pocketbase
          tags: |
            type=semver,pattern={{version}},value=${{ steps.pocketbase.outputs.version }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          build-args: VERSION=${{ steps.pocketbase.outputs.version }}
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
